### PR TITLE
fix: decode route if need

### PR DESCRIPTION
**Pull request by zhanghuajieHIT**
decode route if need

### CODE REVIEW

**Review by chanchann — COMMENTED** [review]
Thanks for your pr. Here's one suggestion:

If is_url_encode is true, you will copy twice, you can write it like this.

```
  std::string route_decode;
  if (CodeUtil::is_url_encode(route))
      route_decode = CodeUtil::url_decode(route);
  else 
      route_decode = route;
```

**Comment by zhanghuajieHIT** [comment]
> Thanks for your pr. Here's one suggestion:
> 
> If is_url_encode is true, it will copy twice, you can write it like this.
> 
> ```
>   std::string route_decode;
>   if (CodeUtil::is_url_encode(route))
>       route_decode = CodeUtil::url_decode(route);
>   else 
>       route_decode = route;
> ```

done

**Comment by chanchann** [comment]
I find that it is not necessary to do this here.

Look at this point : 

https://github.com/wfrest/wfrest/blob/70159e35c6fe0b8c1a12fa292386af3a7d18e98a/src/core/HttpServer.cc#L58

I have registered the encoded path. So we need the encoded url to match and lookup.

Anyway, your code fails unit tests. Sorry for not noticing this last night.

**Comment by zhanghuajieHIT** [comment]
You are right, the pr is not good.
But, if you try the case 24 (24_peer_ip_address.cc), it will fail.
```
curl -v http://172.18.0.1:8888/method2
*   Trying 172.18.0.1:8888...
* Connected to 172.18.0.1 (172.18.0.1) port 8888 (#0)
> GET /method2 HTTP/1.1
> Host: 172.18.0.1:8888
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: application/json
< Date: Mon, 01 Aug 2022 12:49:57 GMT
< Content-Length: 43
< Connection: Keep-Alive
< 
* Connection #0 to host 172.18.0.1 left intact
{"errmsg":"Route Not Found : GET /method2"}
```

**Comment by chanchann** [comment]
Oh,I find the mistake, I will fix it after work. Thanks for your pr again.

**Comment by zhanghuajieHIT** [comment]
> Oh,I find the mistake, I will fix it after work. Thanks for your pr again.

You may missing `url_encode` in the process of adding `route` to `routes_map_`

**Comment by chanchann** [comment]
> > Oh,I find the mistake, I will fix it after work. Thanks for your pr again.
> 
> You may missing `url_encode` in the process of adding `route` to `routes_map_`

Sorry forget to repky you.

First of all, we store the encoded path in our prefix tree, so we don't need to decode the coming url path.

I find that url_encode function convert '/' to %2F. You can check here : https://docs.oracle.com/en/database/oracle/application-express/20.2/aeapi/URL_ENCODE-Function.html

So I just jump this character.

**Pull request merged**
